// Autogenerated from Pigeon (v3.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "plugin_method_channel.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface PluginMethodChannelAPICodecReader : FlutterStandardReader
@end
@implementation PluginMethodChannelAPICodecReader
@end

@interface PluginMethodChannelAPICodecWriter : FlutterStandardWriter
@end
@implementation PluginMethodChannelAPICodecWriter
@end

@interface PluginMethodChannelAPICodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PluginMethodChannelAPICodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PluginMethodChannelAPICodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PluginMethodChannelAPICodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PluginMethodChannelAPIGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    PluginMethodChannelAPICodecReaderWriter *readerWriter = [[PluginMethodChannelAPICodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void PluginMethodChannelAPISetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PluginMethodChannelAPI> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PluginMethodChannelAPI.getBatteryLevel"
        binaryMessenger:binaryMessenger
        codec:PluginMethodChannelAPIGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getBatteryLevelAsDouble:error:)], @"PluginMethodChannelAPI api (%@) doesn't respond to @selector(getBatteryLevelAsDouble:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_asDouble = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api getBatteryLevelAsDouble:arg_asDouble error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PluginMethodChannelAPI.isLowPowerMode"
        binaryMessenger:binaryMessenger
        codec:PluginMethodChannelAPIGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isLowPowerModeWithError:)], @"PluginMethodChannelAPI api (%@) doesn't respond to @selector(isLowPowerModeWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isLowPowerModeWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.PluginMethodChannelAPI.isCharging"
        binaryMessenger:binaryMessenger
        codec:PluginMethodChannelAPIGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isChargingWithError:)], @"PluginMethodChannelAPI api (%@) doesn't respond to @selector(isChargingWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isChargingWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
