// Autogenerated from Pigeon (v3.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by PluginMethodChannelAPI.
NSObject<FlutterMessageCodec> *PluginMethodChannelAPIGetCodec(void);

@protocol PluginMethodChannelAPI
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getBatteryLevelAsDouble:(NSNumber *)asDouble error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isLowPowerModeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isChargingWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void PluginMethodChannelAPISetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PluginMethodChannelAPI> *_Nullable api);

NS_ASSUME_NONNULL_END
